# Get users list 

GET http://localhost:3000/users


###
# Create new user

POST http://localhost:3000/users
content-type: application/json

{
    "name": "homer",
    "email": "homer@simpson.com",
    "password": "je suis le homer"
}


###
# Get a list of boards

GET http://localhost:3000/boards

###
# Create a new board
POST http://localhost:3000/boards
Content-Type: application/json

{
    "name": "first board",
    "userId": 1
}